[package]
name = "cistern"
version = "0.1.0"
authors = ["Markus Reiter <me@reitermark.us>"]
edition = "2018"

[dependencies]
ads1x1x = "*"
embedded-hal = "*"
linux-embedded-hal = "*"
measurements = "0.10"
medianheap = "*"
nb = "*"
rocket = "0.4"
rocket_contrib = { version = "0.4", default-features = false, features = ["json"] }
serde_json = "1"
simple-signal = "1"
