#!/bin/sh

set -e
set -o pipefail
set -o nounset

ip="${1}"

if ssh pi@"${ip}" cat /proc/cpuinfo | grep -q ARMv7; then
  TARGET='armv7-unknown-linux-gnueabihf'
else
  TARGET='arm-unknown-linux-gnueabihf'
fi

cross build --release --target "${TARGET}"

rsync -avz --include cistern --exclude '*' "target/${TARGET}/release/" pi@"${ip}:/tmp/cistern/"

ssh pi@"${ip}" < setup_timezone.sh
ssh pi@"${ip}" < setup_hostname.sh

ssh pi@"${ip}" < setup_i2c.sh
ssh pi@"${ip}" < setup_watchdog.sh

cat <<CONFIG | ssh pi@"${ip}" sudo tee /etc/systemd/system/cistern.service
[Unit]
Description=cistern
StartLimitAction=reboot
StartLimitIntervalSec=60
StartLimitBurst=10

[Service]
Type=simple
Environment=I2C_DEVICE=/dev/i2c-1
Environment=ROCKET_PORT=80
Environment=ROCKET_SECRET_KEY="$(openssl rand -base64 32)"
ExecStart=/usr/local/bin/cistern
Restart=always
RestartSec=1

[Install]
WantedBy=multi-user.target
CONFIG

ssh pi@"${ip}" sudo mv -f /tmp/cistern/cistern /usr/local/bin/cistern
ssh pi@"${ip}" sudo systemctl enable cistern
ssh pi@"${ip}" sudo systemctl restart cistern
